import { Selector } from "@/generated/zeus";

export const eloFields = Selector("v_player_elo")({
  actual_score: true,
  assists: true,
  current_elo: true,
  damage: true,
  damage_percent: true,
  deaths: true,
  elo_change: true,
  expected_score: true,
  impact: true,
  k_factor: true,
  kda: true,
  kills: true,
  map_losses: true,
  map_wins: true,
  match_created_at: true,
  match_id: true,
  match_result: true,
  opponent_team_elo_avg: true,
  performance_multiplier: true,
  player_name: true,
  player_steam_id: true,
  player_team_elo_avg: true,
  series_multiplier: true,
  team_avg_kda: true,
  type: true,
  updated_elo: true,
});
