import { $, order_by, Selector } from "~/generated/zeus";
import { playerFields } from "~/graphql/playerFields";

// All-maps Overview tab. Reads from player_match_stats_v scoped to the
// current match (aggregate across all maps) AND player_match_map_stats
// per-map rows so the row analysis zone can switch between aggregate
// and a single map's numbers via client-side filtering.
export const matchAllMapsStats = Selector("match_lineups")({
  id: true,
  name: true,
  lineup_players: [
    {
      order_by: [
        { captain: order_by.desc_nulls_last },
        { player: { name: $("order_by_name", "order_by!") } },
      ],
    },
    {
      captain: true,
      steam_id: true,
      checked_in: true,
      placeholder_name: true,
      player: {
        ...playerFields,
        match_stats: [
          {
            where: { match_id: { _eq: $("matchId", "uuid!") } },
            limit: 1,
          },
          {
            kills: true,
            hs_kills: true,
            knife_kills: true,
            zeus_kills: true,
            assists: true,
            flash_assists: true,
            deaths: true,
            damage: true,
            team_damage: true,
            he_damage: true,
            molotov_damage: true,
            he_team_damage: true,
            flashes_thrown: true,
            enemies_flashed: true,
            team_flashed: true,
            avg_flash_duration: true,
            two_kill_rounds: true,
            three_kill_rounds: true,
            four_kill_rounds: true,
            five_kill_rounds: true,
            trade_kill_opportunities: true,
            trade_kill_attempts: true,
            trade_kill_successes: true,
            traded_death_opportunities: true,
            traded_death_attempts: true,
            traded_death_successes: true,
            shots_fired: true,
            wasted_magazine_shots: true,
            unused_utility_value: true,
            kills_t: true,
            kills_ct: true,
            hs_kills_t: true,
            hs_kills_ct: true,
            deaths_t: true,
            deaths_ct: true,
            damage_t: true,
            damage_ct: true,
            assists_t: true,
            assists_ct: true,
            rounds_t: true,
            rounds_ct: true,
            hits: true,
            headshot_hits: true,
            avg_time_to_damage_s: true,
            spotted_count: true,
            spotted_with_damage_count: true,
            he_throws: true,
            molotov_throws: true,
            smoke_throws: true,
            decoy_throws: true,
            counter_strafed_shots: true,
            counter_strafe_eligible_shots: true,
            avg_crosshair_angle_deg: true,
            non_awp_hits: true,
            hits_at_spotted: true,
            shots_at_spotted: true,
            spray_shots: true,
            spray_hits: true,
            rounds_played: true,
          },
        ],
        // Per-map breakdown — same fields where they exist on the raw
        // table. The Lineup* tabs read sum/count pairs and compute
        // averages on the fly, so we send those instead of the
        // pre-computed avg_* values (which only exist on the view).
        match_map_stats: [
          {
            where: { match_id: { _eq: $("matchId", "uuid!") } },
          },
          {
            match_map_id: true,
            kills: true,
            hs_kills: true,
            knife_kills: true,
            zeus_kills: true,
            assists: true,
            flash_assists: true,
            deaths: true,
            damage: true,
            team_damage: true,
            he_damage: true,
            molotov_damage: true,
            he_team_damage: true,
            flashes_thrown: true,
            enemies_flashed: true,
            team_flashed: true,
            flash_duration_sum: true,
            flash_duration_count: true,
            two_kill_rounds: true,
            three_kill_rounds: true,
            four_kill_rounds: true,
            five_kill_rounds: true,
            trade_kill_opportunities: true,
            trade_kill_attempts: true,
            trade_kill_successes: true,
            traded_death_opportunities: true,
            traded_death_attempts: true,
            traded_death_successes: true,
            shots_fired: true,
            wasted_magazine_shots: true,
            unused_utility_value: true,
            kills_t: true,
            kills_ct: true,
            hs_kills_t: true,
            hs_kills_ct: true,
            deaths_t: true,
            deaths_ct: true,
            damage_t: true,
            damage_ct: true,
            assists_t: true,
            assists_ct: true,
            rounds_t: true,
            rounds_ct: true,
            hits: true,
            headshot_hits: true,
            time_to_damage_sum_s: true,
            time_to_damage_count: true,
            spotted_count: true,
            spotted_with_damage_count: true,
            he_throws: true,
            molotov_throws: true,
            smoke_throws: true,
            decoy_throws: true,
            counter_strafed_shots: true,
            counter_strafe_eligible_shots: true,
            crosshair_angle_sum_deg: true,
            crosshair_angle_count: true,
            non_awp_hits: true,
            hits_at_spotted: true,
            shots_at_spotted: true,
            spray_shots: true,
            spray_hits: true,
            rounds_played: true,
          },
        ],
      },
    },
  ],
});
